title: Pcrab 的日常
site: https://pcrab.ml

author:
  self_intro: 一个普通的大学生，爱好计算机，懒
  github: Pcrab
  email: pxw0717@gmail.com
  telegram: Pcrab

menus:
  主页: /
  #分类: /categories
  标签: /tags
  关于: /about
  搜索: /search

links:

comment:
  Valine:
    appid: JYGJAIgDkSKSDgp5pUPfyxoO-MdYXbMMI
    appkey: T36nhlVVvMa1c33Tee3F13JM
